### PR TITLE
Xi/fix/add company submission form

### LINKED ISSUE #7: Company submission form (connected to slack)
Popover or other submission on page, that companies can use to send messages to us. (Through slack)

### PR DESCRIPTION
**Pull request by AmiyaSX**
Company submission form that people can send message to contact our sales. (connected to slack channel)
The submission is now connected to channel "it-slack-submission-test"
The form includes "name", "email", "company" and "description", also a ReCaptcha test. 
All the fields are required, email field is restricted in format.

To Test: There are two env variables being added(SLACK_SALES_HOOK_URL, NEXT_PUBLIC_RECAPTCHA_KEY), we should config _.env_ file and add there locally.
image
image

### CODE REVIEW

File: src/app/exhibitor/actions.ts [hunk 1]
```diff
@@ -0,0 +1,41 @@
+"use server"
+import { env } from "@/env"
+import axios from "axios"
+import { z } from "zod"
+
+const ContactSalesSlackSchema = z.object({
```
Comment (AugustPaulsrud) [inline src/app/exhibitor/actions.ts:5]: Nice! Good that you check email

File: src/app/exhibitor/packages/page.tsx [hunk 2]
```diff
@@ -175,6 +176,7 @@ export default async function Packages() {
 						</FAQItem>
 					</Accordion>
 				</div>
+				<CompanySubmissionPopover />
```
Comment (AugustPaulsrud) [inline src/app/exhibitor/packages/page.tsx]: The button is included in all exhibitor pages (/exhibitor), to reduce complexity it could moved to the layout file for the specific sub route (might have to adjust the z index)

File: src/app/exhibitor/_components/CompanySubmissionPopover.tsx [hunk 3]
```diff
@@ -0,0 +1,172 @@
...
+			formData.message !== "" &&
+			isVerified
+		) {
+			setFormFilled(true)
+		} else {
+			setFormFilled(false)
+		}
+	}, [formData, isVerified])
+
+	const handleFieldChange = (event: { target: { name: any; value: any } }) => {
```
Comment (AugustPaulsrud) [inline src/app/exhibitor/_components/CompanySubmissionPopover.tsx]: When possible use function keyword for consistency with codebase

**Review by AugustPaulsrud — COMMENTED** [review]
It looks great, nice work! Good readable code that does what it should. 


I have found some minor issues that will need fixing before merging

image

image

For smaller screen sizes, part of the box is hidden by the menu bar. This could be fixed by reducing the size of the pop up or lowering it's position.


image

The button overlaps with the button for the carousel. Solution would be to change the z index.

File: package.json [hunk 4]
```diff
@@ -14,13 +14,16 @@
...
+		"@radix-ui/react-popover": "^1.0.7",
 		"@radix-ui/react-select": "^2.0.0",
 		"@radix-ui/react-separator": "^1.0.3",
 		"@radix-ui/react-slot": "^1.0.2",
+		"@radix-ui/react-toast": "^1.1.5",
 		"@t3-oss/env-nextjs": "^0.9.2",
 		"@tanstack/react-query": "^5.20.1",
 		"@vercel/analytics": "^1.2.2",
 		"@vercel/speed-insights": "^1.0.10",
+		"axios": "^1.6.8",
```
Comment (hampfh) [inline package.json]: axios is not necessary here, (see comment below regarding the request)

File: src/app/exhibitor/_components/CompanySubmissionPopover.tsx [hunk 5]
```diff
@@ -0,0 +1,172 @@
...
+		name: "",
+		company: "",
+		email: "",
+		message: ""
+	})
+	const [isVerified, setIsVerified] = useState(false)
+	const [formedFilled, setFormFilled] = useState(false)
+	const [isOpen, setIsOpen] = useState(false)
+
+	useEffect(() => {
```
Comment (hampfh) [inline src/app/exhibitor/_components/CompanySubmissionPopover.tsx]: Always give it a second round of thought before using useEffect, it doesn't have to be bad but it makes the code a little harder to read, in this case you could write the same code like this:

```tsx
const [isVerified, setIsVerified] = useState(false)
	//const [formedFilled, setFormFilled] = useState(false)
	const [isOpen, setIsOpen] = useState(false)

    const formFilled = useMemo(() => 
		formData.name !== "" &&
		formData.email !== "" &&
		formData.company !== "" &&
		formData.message !== "" &&
		isVerified, 
        [formData, isVerified]
    )

/* 	useEffect(() => {
		if (
			formData.name !== "" &&
			formData.email !== "" &&
			formData.company !== "" &&
			formData.message !== "" &&
			isVerified
		) {
			setFormFilled(true)
		} else {
			setFormFilled(false)
		}
	}, [formData, isVerified]) */
```

File: src/app/exhibitor/_components/CompanySubmissionPopover.tsx [hunk 6]
```diff
@@ -0,0 +1,172 @@
...
+				</Popover.Trigger>
+				<Popover.Content side="top" side-offset="5">
+					<div className=" rounded-lg p-4 shadow-md filter dark:bg-liqorice-700">
+						<div className="flex flex-col gap-2 p-2">
+							<p className="text-l font-semibold">Contact</p>
+							<fieldset className="flex flex-col">
+								<label className="text-sm" htmlFor="name">
+									Name
+								</label>
+								<input
```
Comment (hampfh) [inline src/app/exhibitor/_components/CompanySubmissionPopover.tsx]: To make input style consistent across browsers, use shadcn input field, that we have in the ui library folder (it works the same way)
CleanShot 2024-05-10 at 14 18 09@2x

File: src/app/exhibitor/_components/CompanySubmissionPopover.tsx [hunk 7]
```diff
@@ -0,0 +1,172 @@
...
+				alert("Submitted! Our sale person will get in touch with you soon!")
+			} else {
+				alert("Submit failed! Please check your email format.")
+			}
+			setIsOpen(false)
+		})
+	}
+
+	return (
+		<div className="fixed bottom-0 mb-6 ml-auto mr-auto md:left-0 md:m-8 md:mx-auto md:ml-16">
```
Comment (hampfh) [inline src/app/exhibitor/_components/CompanySubmissionPopover.tsx]: Make sure the button always have the same padding to the left as to the bottom, for smaller screen sizes, it jumps to the left but doesn't jump down
CleanShot 2024-05-10 at 14 20 23@2x

File: src/app/exhibitor/_components/CompanySubmissionPopover.tsx [hunk 8]
```diff
@@ -0,0 +1,172 @@
...
+		await sendToSlack(formData).then(result => {
+			if (result.success) {
+				// Reset form fields
+				setFormData({
+					name: "",
+					email: "",
+					company: "",
+					message: ""
+				})
+				alert("Submitted! Our sale person will get in touch with you soon!")
```
Comment (hampfh) [inline src/app/exhibitor/_components/CompanySubmissionPopover.tsx]: Instead of using alert you could use shadcn's toast utility, it makes the styles the same in all browsers and is a bit more styled

https://ui.shadcn.com/docs/components/sonner

File: src/app/exhibitor/_components/CompanySubmissionPopover.tsx [hunk 9]
```diff
@@ -0,0 +1,172 @@
...
+		}
+	}
+
+	const sendMessage = async () => {
+		const captchaValue = recaptcha.current.getValue()
+		if (!captchaValue) {
+			alert("Please verify the reCAPTCHA!")
+			return
+		}
+		await sendToSlack(formData).then(result => {
```
Comment (hampfh) [inline src/app/exhibitor/_components/CompanySubmissionPopover.tsx]: You very rarely have to use .then() and .catch(), use only await instead. And if you want to catch you can wrap it in a try/catch block:

```tsx
const result = await sendToSlack(formData)
if (result.success) {
    // ...
}
```

File: src/app/exhibitor/_components/CompanySubmissionPopover.tsx (hunk 6 above)
Comment (Hampfh) [inline src/app/exhibitor/_components/CompanySubmissionPopover.tsx:93]: Here you can use shadcn input field, it works the same way, just use `<Input />` instead of `<input />` and it will get styled correctly

File: src/app/exhibitor/_components/CompanySubmissionPopover.tsx (hunk 7 above)
Comment (Hampfh) [inline src/app/exhibitor/_components/CompanySubmissionPopover.tsx:75]: Make sure the trigger button always has the same padding to the left as to the right, on smaller screen sizes I get this

CleanShot 2024-05-10 at 14 29 20@2x

File: src/app/exhibitor/_components/CompanySubmissionPopover.tsx (hunk 5 above)
Comment (Hampfh) [inline src/app/exhibitor/_components/CompanySubmissionPopover.tsx:22]: Always think a second time if you really need a useEffect, sometimes you can make the same thing without it, useEffect doesn't have to be bad but it will make it harder to read and understand the code. In this case the same behavior could be reached by deriving the data like this:

```tsx
//const [formedFilled, setFormFilled] = useState(false)
	const [isOpen, setIsOpen] = useState(false)

	const formFilled = useMemo(() => 
		formData.name !== "" &&
		formData.email !== "" &&
		formData.company !== "" &&
		formData.message !== "" &&
		isVerified, [formData, isVerified])

	/*useEffect(() => {
		if (
			formData.name !== "" &&
			formData.email !== "" &&
			formData.company !== "" &&
			formData.message !== "" &&
			isVerified
		) {
			setFormFilled(true)
		} else {
			setFormFilled(false)
		}
	}, [formData, isVerified]) */
```

File: src/app/exhibitor/actions.ts [hunk 10]
```diff
@@ -0,0 +1,41 @@
...
+		return { success: false }
+	}
+	const msg = {
+		text: `
+        # New External Contact Message #\n*Name:* ${args.name}\n*Email:* ${args.email}\n*Company:* ${args.company}\n*Description:*\n${args.message
+					.split("\n")
+					.map(line => `>${line}`)
+					.join("\n")}\n`
+	}
+	axios
```
Comment (hampfh) [inline src/app/exhibitor/actions.ts]: Here you don't need axios, you can write the same thing using fetch which is built in:

```tsx
try {
	const response = await fetch(env.SLACK_SALES_HOOK_URL, {
		body: msg,
		headers: {
			"Content-Type": "application/json"
		}
	})
    const data = await response.json()
    console.log("Message sent successfully:", data)
} catch (error) {
		console.error("Error sending message:", error)
}
```

**Review by hampfh — COMMENTED** [review]
Thank you Xi and great job on the submission form! This has been requested since we switched to the new site

I've left comments on code style etc which I think you can fix quite easily, if there is something that you don't agree with or do not understand feel free to send me a message :)

File: src/app/exhibitor/packages/page.tsx (hunk 2 above)
Comment (hampfh) [reply src/app/exhibitor/packages/page.tsx]: I agree, this is the file you want to add it to:

CleanShot 2024-05-10 at 14 47 32@2x

**Review by hampfh — APPROVED** [review]
Great job overall an on the feedback, thanks Xi for the fixes, ready to merge!
