### PR TITLE
Valdemar/fix/improve timeline

### LINKED ISSUE #26: Refractor the for companies timeline
Refractor the for companies timeline (https://armada.nu/exhibitor/timeline) to:
- reduce duplicate code (not defining how  a event on the timeline should look for each part of the timeline but just doing so once)
-  switch to the improved dropdowns used on the recruitment page https://armada.nu/student/recruitment

### PR DESCRIPTION
**Pull request by vmork**
Fixes #26

Also changed faq on exhibitor/packages to use same animated accordion component as the timeline and recruitment page.

### CODE REVIEW

File: src/app/exhibitor/_components/ExhibitorTimeline.tsx [hunk 1]
```diff
@@ -1,396 +1,226 @@
...
+					<Link
+						className="text-white underline hover:no-underline"
+						href="/exhibitor/packages">
+						here
+					</Link>{" "}
+					to give you an overview. Prices are set, and small changes can occur
+					in the larger packages.
+				</P>
+				<div className="my-4">
+					<a href="https://register.armada.nu/register">
```
Comment (hampfh) [inline src/app/exhibitor/_components/ExhibitorTimeline.tsx]: nextjs has a builtin `<Link>` component which provides some optimizations, I'm aware that this was here already but it would be great if it could be fixed in this PR

Comment (hampfh) [reply src/app/exhibitor/_components/ExhibitorTimeline.tsx]: https://nextjs.org/docs/app/api-reference/components/link

File: src/app/exhibitor/_components/ExhibitorTimeline.tsx [hunk 2]
```diff
@@ -1,396 +1,226 @@
...
+					We will get back to everyone who made an Initial Registration by{" "}
+					{formatDate(dates.ir.end)}. This is when you will know 100% for sure
+					that you are exhibiting at Armada. You will be informed by email to
+					the person who made the Final Registration, and it will be visible on
+					the dashboard for anyone with a login to your exhibitor&apos;s page.
+				</P>
+				<P className="text-stone-400">
+					You can always check the status of your registration on the dashboard,
+					and contact{" "}
+					<a
```
Comment (hampfh) [inline src/app/exhibitor/_components/ExhibitorTimeline.tsx]: `<Link>`

File: src/app/exhibitor/_components/ExhibitorTimeline.tsx [hunk 3]
```diff
@@ -1,396 +1,226 @@
...
+				title="Final Registration starts">
+				<P className="mt-3 text-stone-400">
+					During the Final Registration you choose your package, if you want to
+					do any events, number of tickets for the banquet etc. All of this is
+					done on the registration dashboard - same as where you did Initial
+					Registration. Final Registration can be done by another person than
+					Initial Registration.
+				</P>
+				<div className="my-4">
+					<a href="https://register.armada.nu/register">
```
Comment (hampfh) [inline src/app/exhibitor/_components/ExhibitorTimeline.tsx]: `<Link>`

File: src/app/exhibitor/_components/ExhibitorTimeline.tsx [hunk 4]
```diff
@@ -1,396 +1,226 @@
...
+						<Button>Signup to Armada</Button>
+					</a>
+				</div>
+				<P className="mt-3 text-stone-400">
+					We have many different products that help you reach students at KTH in
+					different ways. If you want help finding the best package for you,
+					please contact{" "}
+					<a
```
Comment (hampfh) [inline src/app/exhibitor/_components/ExhibitorTimeline.tsx]: `<Link>`

File: src/app/exhibitor/_components/TimelineItem.tsx [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+export function TimelineItem({
+	children,
+	title,
+	dateString
+}: {
+	children?: React.ReactNode
+	title: string
+	dateString: string
+}) {
+	const expandable = children != null
```
Comment (hampfh) [inline src/app/exhibitor/_components/TimelineItem.tsx:18]: Nice 👍

File: src/app/exhibitor/_components/TimelineItem.tsx [hunk 6]
```diff
@@ -0,0 +1,46 @@
...
+			key={title}
+			value={title}
+			disabled={!expandable}
+			className="border-none">
+			<div className="absolute -start-1.5 mt-3.5 h-3 w-3 rounded-full border border-white bg-melon-700"></div>
+			<AccordionTrigger
+				disabled={!expandable}
+				className={cn(
+					"mb-2 ml-4 w-full rounded px-2 pb-4 pt-0 text-left font-normal hover:no-underline",
+					expandable && "transition hover:bg-slate-700"
```
Comment (hampfh) [inline src/app/exhibitor/_components/TimelineItem.tsx]: this works, but the preferred convention here would be:

```tsx
cn("mb-2 ml-4 w-full rounded px-2 pb-4 pt-0 text-left font-normal hover:no-underline", {
    "transition hover:bg-slate-700": expandable
}}
```

this is the same thing logically but a little more readable

File: src/app/exhibitor/packages/page.tsx [hunk 7]
```diff
@@ -18,6 +19,25 @@ export const metadata: Metadata = {
 		"The packages we offer for exhibitors at Armada. Choose between bronze, silver and gold."
 }
 
+function FAQItem({
```
Comment (hampfh) [inline src/app/exhibitor/packages/page.tsx:22]: I really like this abstraction 👍

File: src/app/exhibitor/packages/page.tsx [hunk 8]
```diff
@@ -18,6 +19,25 @@ export const metadata: Metadata = {
...
+	children,
+	title
+}: {
+	children: React.ReactNode
+	title: string
+}) {
+	return (
+		<AccordionItem key={title} value={title} className="border-none">
```
Comment (hampfh) [inline src/app/exhibitor/packages/page.tsx]: the `key` prop here doesn't really do anything since it is not in a list, hence it can be removed, if we want to apply this component to a list we set the key prop of the entire component outside this function instead of inside

File: src/app/exhibitor/packages/page.tsx [hunk 9]
```diff
@@ -112,83 +132,48 @@ export default async function Packages() {
...
-								fair where there is good footfall. Gold exhibitors take the best
-								spots and silver exhibitors are prioritized next. Contact{" "}
-								<a
+					<h1 className="ml-2 mb-2 text-2xl">FAQ</h1>
+					<Accordion type="single" collapsible={true}>
+						<FAQItem title='What does "priority placement" mean?'>
+							Priority placement means that we will place you in spots on the
+							fair where there is good footfall. Gold exhibitors take the best
+							spots and silver exhibitors are prioritized next. Contact{" "}
+							<a
```
Comment (hampfh) [inline src/app/exhibitor/packages/page.tsx]: `<Link>`

File: src/components/ui/accordion.tsx [hunk 10]
```diff
@@ -34,7 +34,7 @@ const AccordionTrigger = React.forwardRef<
       {...props}
     >
       {children}
-      <ChevronDown className="h-4 w-4 shrink-0 transition-transform duration-200" />
+      {!disabled && <ChevronDown className="h-4 w-4 shrink-0 transition-transform duration-200" />}
```
Comment (hampfh) [inline src/components/ui/accordion.tsx:37]: neat!

**Review by hampfh — COMMENTED** [review]
Great PR, I think the code is a lot more readable now after these abstractions, good job!

I left a couple of comments regarding some conventions that I'd like you to take a look at. I also saw that we have left a couple of <a> tags in the code which I think is a great time to replace here. These are just some minor changes

Great work!

**Review by hampfh — APPROVED** [review]
Great job ✅ 
Ready to merge
